#!/bin/sh

#************************************************#
#                 ytfeeder.sh                    #
#                                                #
#           Convert youtube takeout CSVs         #
#           to RSS                               #
#************************************************#

TAKEOUT_LOCATION='' # Youtube takeout location
FRONTEND=''         # TODO: Support alternative frontends
OPML=0              # Whether to output as opml

# --------------------------------------------------------- #
# getChannelIDs ()                                          #
# Echo channel IDs separated by spaces by                   #
# looking through $TAKEOUT_LOCATION                         #
# Parameter:                                                #
#   $1: Takeout csv location                                #
# --------------------------------------------------------- #
getChannelIDs() {
  if [ -f $1 ] && [ -r $1 ]; then
    echo $(cat "$1" | sed -E '1d; s/(,.+)/ /')
  fi
}

# --------------------------------------------------------- #
# toRSSYoutube ()                                           #
# Echos youtube RSS feeds                                   #
# Parameter:                                                #
#   $1: Youtube channel IDs, separated by spaces            #
# --------------------------------------------------------- #
toRSSYoutube() {
  until [ -z $1 ]; do
    echo "https://youtube.com/feeds/videos.xml?channel_id=$1"
    shift
  done
}

# --------------------------------------------------------- #
# toOPML ()                                                 #
# Echos an OPML subscription list                           #
# Parameter:                                                #
#   $1: RSS subscriptions, separated by newlines            #
# --------------------------------------------------------- #
toOPML() {
  local OUTLINES=''

  until [ -z $2 ]; do
    OUTLINES+="    <outline xmlUrl=\"$1\" />\n"
    shift
  done
  OUTLINES+="    <outline xmlUrl=\"$1\" />"

  printf \
    "<opml version=\"2.0\">
<head>
  <title>YouTube Subscriptions</title>
</head>
  <body>
$OUTLINES
  </body>
</opml>
"
}

if [ ! -z $1 ]; then
  until [ -z $1 ]; do
    case $1 in
    '-i' | '--input')
      TAKEOUT_LOCATION="$2"
      shift 2
      ;;
    '-f' | '--front-end')
      FRONTEND="$2"
      shift 2
      ;;
    '-O' | '--opml')
      OPML=1
      shift 1
      ;;
    *)
      echo >&2 "Unknown argument"
      exit 1
      ;;
    esac
  done
  if [  "$OPML" -ne '0' ]; then
    toOPML $(toRSSYoutube $(getChannelIDs $TAKEOUT_LOCATION))
  else 
    toRSSYoutube $(getChannelIDs $TAKEOUT_LOCATION)
  fi
else
  echo "Help"
fi
