#!/bin/sh


#************************************************#
#                 ytfeeder.sh                    #
#                                                #
#           Convert youtube takeout CSVs         #
#           to RSS                               #
#************************************************#



TAKEOUT_LOCATION=''   # Youtube takeout location
FRONTEND=''           # TODO: Support alternative frontends

# --------------------------------------------------------- #
# getChannelIDs ()                                          #
# Echo channel IDs separated by spaces by                   # 
# looking through $TAKEOUT_LOCATION                         #
# Parameter:                                                #
#   $1: Takeout csv location                                # 
# --------------------------------------------------------- #
getChannelIDs() {
  if [ -f $1 ] && [ -r $1 ]; then
    echo $(cat "$1" | sed -E '1d; s/(,.+)/ /')
  fi
}

# --------------------------------------------------------- #
# toRSSYoutube ()                                           #
# Echos youtube RSS feeds                                   #
# Parameter:                                                #
#   $1: Youtube channel IDs, separated by spaces            #
# --------------------------------------------------------- #
toRSSYoutube() {
  until [ -z $1 ]; do
    echo "https://youtube.com/feeds/videos.xml?channel_id=$1"
    shift
  done
}

if [ ! -z $1 ]; then
  until [ -z $1 ]; do
    case $1 in
    '-i' | '--input')
      TAKEOUT_LOCATION="$2"
      shift 2
      ;;
    '--front-end')
      FRONTEND="$2"
      shift 2
      ;;
    *)
      echo >&2 "Unknown argument"
      exit 1
      ;;
    esac
  done
  toRSSYoutube $(getChannelIDs $TAKEOUT_LOCATION)
else
  echo "Help"
fi
